export default {
    NONE: '无',
    COLOR_OFFSET: '颜色偏移(*)',
    // NEGATIVE: '反色',
    // DOUBLE: '2D',
    // BINARY: '二值化(*)',
    ATOMIZATION: '雾化(*)',
    MOSIC: '马赛克',
    // RADIUS_LIGHT: '径向光照(*)',
    // SWIRL: '扭曲(*)',
    GAUSSIAN: '高斯模糊',
    // GLOW: '发光(*)',
    ANTIQUE: '古色',
    // INKWELL: '新黑白',
    // MASK: 'mask',
    // MONO: '黑白2',
    // IOSBLUR: '亮度减少',
    GAUSSAIN2: '高斯模糊2',
    // SKETCH: 'sketch',
    STENCIL: '蒙版',
    SUNSET: '日落',
    WARM: '温暖',
    GANGFENG: '剪映-港风',
    JUEDUIHONG: '剪映-绝对红',
    LENGPAN: '剪映-冷盘',
    MOPIAN: '剪映-默片',
    NINGMENGQING: '剪映-柠檬青',
    RILUOJU: '剪映-日落橘',
    SAIBO: '剪映-赛博朋克',
    WUHOU: '剪映-午后',
    XIARIZHONGQU: '剪映-夏日终曲',
    XIANLIANG: '剪映-鲜亮',
    ZHENGQIBO: '剪映-蒸汽波',
    ZHONGXIA: '剪映-仲夏',
    JY1970: '剪映-1970',
    BLUES: '剪映-BLUES',
    CHUJIAN: '剪映-初见',
    CHUANGGUANGZHAXIE: '剪映-春光乍泄',
    DUNKEERKE: '剪映-敦刻尔克',
    FUSHI: '剪映-富士',
    HONGYULAN: '剪映-红与蓝',
    JZH: '剪映-江浙沪',
    KEKOU: '剪映-可口',
    LUOYEZONG: '剪映-落叶棕',
    MUJI: '剪映-MUJI',
    MUSE: '剪映-暮色',
    NIHONGGUANG: '剪映-霓虹光',
    NIUPIZHI: '剪映-牛皮纸',
    QINGKONG: '剪映-晴空',
    QINGTOU: '剪映-清透',
    RISHI: '剪映-日食',
    SHANGWEI: '剪映-赏味',
    VINTAGE: '剪映-VINTAGE',
    WENXIANGSHIREN: '剪映-闻香识人',
    WUSHAN: '剪映-雾山',
    XIAOZHUN: '剪映-小樽',
    YUANTU: '剪映-远途',
    ZIRAN: '剪映-自然'
    
}