export default {
    COLOR_OFFSET: '颜色偏移(*)',
    NEGATIVE: '反色',
    DOUBLE: '2D',
    BINARY: '二值化(*)',
    ATOMIZATION: '雾化(*)',
    MOSIC: '马赛克',
    RADIUS_LIGHT: '径向光照(*)',
    SWIRL: '扭曲(*)',
    // GAUSSIAN: '高斯模糊',
    GLOW: '发光(*)',
    ANTIQUE: '古色',
    INKWELL: '新黑白',
    // MASK: 'mask',
    // MONO: '黑白2',
    IOSBLUR: '亮度减少',
    GAUSSAIN2: '高斯模糊2',
    // SKETCH: 'sketch',
    STENCIL: '蒙版',
    SUNSET: '日落',
    WARM: '温暖',
    GANGFENG: '剪映-港风'
}